 - name: install cron job (ansible-pull)
   cron:
     user: ansibot
     name: "ansible provision"
     minute: "*/59"
     job: "ansible-pull -o -U https://github.com/thr3swe/ansipull.git > /dev/null"
