 - name: install cron job (ansible-pull)
   cron:
     user: ansible
     name: "ansible provision"
     minute: "*/59"
     job: "/usr/bin/ansible-pull -o -U https://github.com/thr3swe/ansipull.git > /dev/null"
