- name: system setup | utilities | install utility packages
  tags: packages,system,settings
  package:
    state: latest
    name:
      - htop
      - tmux
      - zsh
      - colordiff
      - neofetch
      - net-tools
      - nmap
      - curl
      - "{{ vim_package }}"
      - sshpass
