- include_vars: "{{ ansible_distribution }}.yml"
  tags: always

- block:
  # Make sure users exist on the system
  - import_tasks: users/ansibot.yml
  
  # install software
  - import_tasks: software/packages_utilities.yml
