- include_vars: "{{ ansible_distribution }}.yml"
  tags: always

  # install software
  - import_tasks: software/repositories.yml
  - import_tasks: software/packages_development.yml
  - import_tasks: software/packages_cleanup.yml
  - import_tasks: software/packages_pip.yml
  - import_tasks: software/packages_utilities.yml
